# Generated by Django 3.1 on 2020-08-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200815_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='use_name',
            new_name='username',
        ),
    ]
