# Generated by Django 3.1 on 2020-08-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20200826_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
