# Generated by Django 3.1 on 2020-08-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='UserProfile',
        ),
    ]
